### ISSUE TITLE
Difference with khard

### ISSUE THREAD

**Issue by DamienCassou** [untitaker/mates.rs#13]
I was wondering what could be the differences between mates and [khard](https://github.com/scheibler/khard/). It seems both have been created 1 year ago. Are there different use cases?

**Comment by DamienCassou** [comment]
I asked the same question at https://github.com/scheibler/khard/issues/29

**Comment by untitaker** [comment]
khard has way more features than mates, yet I consider mates to be more stable and less complex.

If you find the current featureset of mates to be sufficient, use it, but for most ppl it isn't.

On 28 October 2015 06:37:44 CET, Damien Cassou <notifications@github.com> wrote:
>I was wondering what could be the differences between mates and
>[khard](https://github.com/scheibler/khard/). It seems both have been
>created 1 year ago. Are there different use cases?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/untitaker/mates.rs/issues/13

-- 
Sent from my phone. Please excuse my brevity.
