### ISSUE TITLE
Remove dependency to git

### ISSUE THREAD

**Issue by DamienCassou** [untitaker/mates.rs#14]
To facilitate packaging of mates.rs, it would be better if mates dependencies would be in crates.io. The problem is discussed at https://github.com/NixOS/nixpkgs/pull/10661

**Comment by untitaker** [comment]
Binary support for crates.io is still in beta, and the Cargo.lock pins all dependencies. If you pin to the correct tag, hash mismatches shouldn't occur accidentally.

If rust 1.5 lands I'll release the next version of mates through crates.io, but OTOH I don't see a need to.

**Comment by untitaker** [comment]
Is now on crates.io, also tagged in git. See README for usage. `cargo install` also has flags that allow installation with a custom prefix (for packaging purposes).
