### ISSUE TITLE
fail to compile with cargo

### ISSUE THREAD

**Issue by quite** [untitaker/mates.rs#6]
I'm trying to compile mates.

cargo 0.0.1-pre-nightly (2422edc 2015-01-19 07:28:44 +0000)

cargo build yields.
   Compiling atomicwrites v0.0.2
   Compiling rustc-serialize v0.2.10
/home/quite/.cargo/registry/src/github.com-1285ae84e5963aae/atomicwrites-0.0.2/src/lib.rs:4:5: 4:16 error: unresolved import `std::old_io`. There is no `old_io` in `std`
/home/quite/.cargo/registry/src/github.com-1285ae84e5963aae/atomicwrites-0.0.2/src/lib.rs:4 use std::old_io;
                                                                                                ^~~~~~~~~~~
error: aborting due to previous error
   Compiling peg v0.1.5
/home/quite/.cargo/registry/src/github.com-1285ae84e5963aae/rustc-serialize-0.2.10/src/json.rs:251:27: 251:33 error: unresolved import `std::old_io`. There is no `old_io` in `std`
/home/quite/.cargo/registry/src/github.com-1285ae84e5963aae/rustc-serialize-0.2.10/src/json.rs:251 use std::{char, f64, fmt, old_io, num, str};
                                                                                                                             ^~~~~~
error: aborting due to previous error
   Compiling gcc v0.1.7
/home/quite/.cargo/registry/src/github.com-1285ae84e5963aae/gcc-0.1.7/src/lib.rs:3:5: 3:25 error: unresolved import `std::old_io::Command`. Could not find `old_io` in `std`
/home/quite/.cargo/registry/src/github.com-1285ae84e5963aae/gcc-0.1.7/src/lib.rs:3 use std::old_io::Command;
                                                                                       ^~~~~~~~~~~~~~~~~~~~
/home/quite/.cargo/registry/src/github.com-1285ae84e5963aae/gcc-0.1.7/src/lib.rs:4:5: 4:36 error: unresolved import `std::old_io::process::InheritFd`. Could not find `old_io` in `std`
/home/quite/.cargo/registry/src/github.com-1285ae84e5963aae/gcc-0.1.7/src/lib.rs:4 use std::old_io::process::InheritFd;
                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to 2 previous errors
   Compiling getopts v0.2.0
/home/quite/.cargo/registry/src/github.com-1285ae84e5963aae/peg-0.1.5/src/peg_syntax_ext.rs:13:5: 13:26 error: unresolved import `std::old_io::fs::File`. Could not find `old_io` in `std`
/home/quite/.cargo/registry/src/github.com-1285ae84e5963aae/peg-0.1.5/src/peg_syntax_ext.rs:13 use std::old_io::fs::File;
                                                                                                   ^~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
/home/quite/.cargo/registry/src/github.com-1285ae84e5963aae/getopts-0.2.0/src/lib.rs:658:6: 658:18 error: attempt to implement a nonexistent trait `fmt::Display`
/home/quite/.cargo/registry/src/github.com-1285ae84e5963aae/getopts-0.2.0/src/lib.rs:658 impl fmt::Display for Fail {
                                                                                              ^~~~~~~~~~~~
error: aborting due to previous error
Could not compile `atomicwrites`.

To learn more, run the command again with --verbose.

**Comment by untitaker** [comment]
I think both cargo and rust are out-of-date on your machine.

**Comment by untitaker** [comment]
IOW the alpha version of Rust is unfortunately not enough. I used to track the alpha version, but it appears every library I depend on tracks nightly, which makes it impossible to track alpha for me.

**Comment by quite** [comment]
Yep, rust 1.0.0.alpha-3 in Arch Linux was not enough. Latest nightly did it.

Danke.

**Comment by untitaker** [comment]
On Arch, mates-git is available in the AUR.
